name: Update Server keys

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Debug print job name
        run: echo "Job name is ${{ github.job }}"
